# Generated by Django 3.2 on 2021-04-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210422_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isbn',
            name='created_at',
        ),
    ]
